spring:
  application:
    name: snowboard-lesson-booking
  profiles:
    active: dev
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${SPRING_MAIL_USERNAME}
    password: ${SPRING_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  datasource:
    driver-class-name: ${snowboard.driver-class-name}
    url: jdbc:mysql://${snowboard.host}:${snowboard.port}/${snowboard.database}?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: ${snowboard.username} # 你的开发数据库用户名
    password: ${snowboard.password}
  jpa:
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  servlet:
    multipart:
      max-file-size: 5MB   # 设置单个文件最大为5MB
      max-request-size: 20MB # 设置单次请求最大为20MB (例如一次上传多个证书)
aws:
  s3:
    bucket-name: ${AWS_S3_BUCKET_NAME}
    region: ${AWS_S3_REGION}
    access-key-id: ${AWS_S3_ACCESS_KEY_ID}
    access-key-secret: ${AWS_S3_ACCESS_KEY_SECRET}
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
server:
  port: 8080
snowboard:
  jwt:
    secret-key: ${JWT_SECRET_KEY}
    ttl: 86400000

